- hosts: all 
  gather_facts: False
  
  tasks:
          - name: install python 2 
            become: yes
            raw: sudo bash -c "test -e /usr/bin/python || (apt-get update && apt-get install -y python-minimal)"
