# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  # install python so ansible is happy
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "pre-prov.yml"
  end
  # actually provision the machine to how I like
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "tunestore_setup.yml"
  end
  # owasp zap
  # config.vm.provision :ansible do |ansible|
  #   ansible.playbook = "tunestore_zap.yml"
  # end
  config.ssh.forward_x11 = true
  config.vm.network "forwarded_port", guest: 8080, host: 8090, host_ip: "127.0.0.1", auto_correct: true
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
  end
end
